### ISSUE TITLE
All Games

### ISSUE THREAD

**Issue by timea-techgirl** [Tzirrit/ExanimaSavegameManager#6]
Hello,
Can you make this work with any selected folder and backup the files inside it?

Thanks!

**Comment by Tzirrit** [comment]
Do you mean storing Exanima savegames to any folder?
- This can already be done by changing the backup folder in the settings.

Or do you mean backing up savegames (files) from any other game?
- That would be a bit out of scope for this tool.

**Comment by timea-techgirl** [comment]
For example, I'm playing assassin's creed. I want my save folder to be backed up automatically. Isn't that possible with this?

**Comment by Tzirrit** [comment]
I never playerd Assassin's Creed, so I don't know how it handles save games.
Feel free to take toe code and tweak it to work with any other game you want ;)
